language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database travistestdb;' -U postgres
  - python manage.py migrate --settings=locallibrary.settings.test
script:
  - coverage run --source=api manage.py test --settings=locallibrary.settings.test
  - flake8 .
after_success:
  - coveralls
notifications:
  matrix:
    - slack
  slack:
    secure: GbJcJZh4w32r8SMu9JB3FwyHBkWLS+cXMboXp+8Xfq8dMgQkmNkaEnurydxpdwi9cJED547ORRzwzTzrMjeD1dkxg4m7StdJTLR60EBdfFqMx8ROSAg0qVQjrY7/tf/eqKTIoB1Qx5GVKzpNLG8QqOZ1z3mqCSrRlacc6FFudQUOyfHvPuray5BISsdJl0VA6va4FahcRvu1tP1qY1Fz1GXXnPugDJ/lfitxo0xz5dobfKDux8r9HF97sR0LnGDIS7Jjt4ebm49yJbsD2XfMx7gkcfYTUGx24d/5INDBPjDpRPHblGss2f3KeSSmFg/POpoBSmuhz2JOgcikLHNnhrRVve3bFWLBa0hxwoIyiE8kpb/yobHlQRjnaLG67hihO56CMmCxiwB/X4T/lGgMhA6IwcNPDSjF/lOOKbxU0EjD9HJSXuCK+K9fxcJQr3JO/DfOr3pCYpu90OKFkv4Y3RW1xVAMsX2z1nvAUdZrhaGZOvgiQMXp4PUzKhQlVgDo6cGY/FncTqWEVwl2AdNgFAlsxBHyNGpBfFyA5TgFJJqHM2GvKRpFBLkxUSHfohS/MKWeFtbuK6qFGP02XVcPA70mcFkJW1LZSihcnMFHLdVDoPVaRq4R9i3VBQBH7q5DNxlCtum7WptuAOip318hFJCupBZvZ2XsUmcK+N7urdA=
deploy:
  provider: heroku
  api_key:
    secure: Vv24nZIKm4iqb8rDyGNcUY7UJ6IVvaqnovrkX1S1ATFRqP2SXp3+HiLHfrFm6Z03OJYfOvgYbzsxjFh17sJOFnSfxyKyGZq02TKtj0uAYd3vQ9et8cNebWjbAa3rTaWYL5Yh/Y7V09A2UMAHm1rSXWt0TJx1iPaMNn5iet6012iZ7a/PScQ2k5FpGOFpNRwwD8uh0SkmjHNXV3ovzhDwKt2K37Lj16HvqB2L2ayJ2eJkFKQmCThnBpJdvcfaLGdpsMH4RE1VhKmBg2ihx8almlbpAom8LL+2P1/Ue6KZLXd73XNOgwKnQdHUXyp5Fyow4NogzsGnB/o40o1IlUSynTfK7IQeHVErlYj3mgOBi9Nyfh94XW5WO/x4gihdC/IMgxILG8WYduz3LDTzpOhxY4BG/ItNGk4lM/LF06F28w5mgIzJdTX8fQBNwp7EBiww5JF9mVKpDsLMLDjDKMKL034qlrPaAyh2bYA4IbuVfDl58dp0g1LIRaA+dzw9inczMr9+4UoPyEYzRJWxWe39zYPvUnLIhIAa0tWUnE3wSUsLOTdTZbUAJLKyEK+ts2l61DcltXtgx1bnlUwA6xNt9mL1fP17nEKsfty5Z1FG8UBIEo++qn1zpbw4NqKrV+K/Bb6wHxIQQ3EnD3iCuYZC2NpeZQxAjt6m57FGAHchxtw=
  app:
    main: moz-locallibrary
  run:
    - python manage.py migrate --noinput
