language: python
python:
- 3.6
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travistestdb;' -U postgres
- python manage.py migrate --settings=locallibrary.settings.test
script:
- coverage run --source=api manage.py test --settings=locallibrary.settings.test
- flake8 .
after_success:
- coveralls
notifications:
  matrix:
  - slack
  slack:
    secure: GbJcJZh4w32r8SMu9JB3FwyHBkWLS+cXMboXp+8Xfq8dMgQkmNkaEnurydxpdwi9cJED547ORRzwzTzrMjeD1dkxg4m7StdJTLR60EBdfFqMx8ROSAg0qVQjrY7/tf/eqKTIoB1Qx5GVKzpNLG8QqOZ1z3mqCSrRlacc6FFudQUOyfHvPuray5BISsdJl0VA6va4FahcRvu1tP1qY1Fz1GXXnPugDJ/lfitxo0xz5dobfKDux8r9HF97sR0LnGDIS7Jjt4ebm49yJbsD2XfMx7gkcfYTUGx24d/5INDBPjDpRPHblGss2f3KeSSmFg/POpoBSmuhz2JOgcikLHNnhrRVve3bFWLBa0hxwoIyiE8kpb/yobHlQRjnaLG67hihO56CMmCxiwB/X4T/lGgMhA6IwcNPDSjF/lOOKbxU0EjD9HJSXuCK+K9fxcJQr3JO/DfOr3pCYpu90OKFkv4Y3RW1xVAMsX2z1nvAUdZrhaGZOvgiQMXp4PUzKhQlVgDo6cGY/FncTqWEVwl2AdNgFAlsxBHyNGpBfFyA5TgFJJqHM2GvKRpFBLkxUSHfohS/MKWeFtbuK6qFGP02XVcPA70mcFkJW1LZSihcnMFHLdVDoPVaRq4R9i3VBQBH7q5DNxlCtum7WptuAOip318hFJCupBZvZ2XsUmcK+N7urdA=
deploy:
  provider: heroku
  api_key:
    secure: EPwxd4Hr659tUME9Jt1w/pQo/8AKQ6JrvbIOYlAYI8k8oV9qB1os9alo9zB3wK3NnvwY4I+KbC/LCGqhgb4VOUVd1O5hN/VB9fs7IpRxO7/Qs6EELA4pzzC69p5nRaC+b23YHBUnX2goeEZFmG+4KYrGt569Oqi85uXoAh2lwrGJQOeFap1vvQk4bwsQb3E8frdl8djyJRk8PbEHb/i0D24lT2JUSgUBUCjbj/t0xtJQQK68QpDTrRlZR+R+VAPrkrWkJOb3hcwAFtwuIOpD42tXumTPdxKbP+a/IbSq6mtoPtm2U19QDM4blYT2gss8pncSDWD2QX+O8DxXygmPXg9yMmpr4ATfub6yhnuAZiJJppT1A9WelY5ZyUPLBWcaX9GqVlWrre5PXUMbUUvbbHTkdpdm8i2NNYNJYR0BGCAa0kJvvnH30NK5DDtrGIDVfmx6tneUzSE558rkp8JBdNuiwrAZlSTXb87Z0iNOQSEs2MhP5yUjsK5gx17MxaGEyIxMzBys+lnVQ9Bcje/RyzEWrYDnSvjCjROI8Lajy9wWAVu+vgT991QJuqkOggyAdqX73J1XzpkK6x4LlAdJ0uVB9k/AiQsQPVcUR66hH+bXBNH07wFdKxGwn5q7C+X2wVd2buHonHsBGnbf+p1Th0hFL3xVCLXjKwvnoptwVCs=
  app:
    main: moz-locallibrary
  run:
  - python manage.py migrate --noinput
