language: python
python:
- 3.6
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travistestdb;' -U postgres
- python manage.py migrate --settings=locallibrary.settings.test
script:
- coverage run --source=api manage.py test --settings=locallibrary.settings.test
- flake8 .
after_success:
- coveralls
notifications:
  matrix:
  - slack
  slack:
    secure: GbJcJZh4w32r8SMu9JB3FwyHBkWLS+cXMboXp+8Xfq8dMgQkmNkaEnurydxpdwi9cJED547ORRzwzTzrMjeD1dkxg4m7StdJTLR60EBdfFqMx8ROSAg0qVQjrY7/tf/eqKTIoB1Qx5GVKzpNLG8QqOZ1z3mqCSrRlacc6FFudQUOyfHvPuray5BISsdJl0VA6va4FahcRvu1tP1qY1Fz1GXXnPugDJ/lfitxo0xz5dobfKDux8r9HF97sR0LnGDIS7Jjt4ebm49yJbsD2XfMx7gkcfYTUGx24d/5INDBPjDpRPHblGss2f3KeSSmFg/POpoBSmuhz2JOgcikLHNnhrRVve3bFWLBa0hxwoIyiE8kpb/yobHlQRjnaLG67hihO56CMmCxiwB/X4T/lGgMhA6IwcNPDSjF/lOOKbxU0EjD9HJSXuCK+K9fxcJQr3JO/DfOr3pCYpu90OKFkv4Y3RW1xVAMsX2z1nvAUdZrhaGZOvgiQMXp4PUzKhQlVgDo6cGY/FncTqWEVwl2AdNgFAlsxBHyNGpBfFyA5TgFJJqHM2GvKRpFBLkxUSHfohS/MKWeFtbuK6qFGP02XVcPA70mcFkJW1LZSihcnMFHLdVDoPVaRq4R9i3VBQBH7q5DNxlCtum7WptuAOip318hFJCupBZvZ2XsUmcK+N7urdA=
deploy:
  provider: heroku
  api_key:
    secure: YJ2hKlZZwjNpJwJdEozk1yTugKOx4Iy8U/5gz9WIhqwsGAjdEugO2y+Kxqx4uDVxdgpQlKM81U1RqfheYhQPDGeXBe6Z1yoGnEyvqNdRnW9D9OM6o3Q94/HZyBbRnqXrbwJNQD2L2GPb2FkvtAZn76+iTIeng7Pn2Kk7s7hr/3dRZIOLXyGxmcJPvPAMKdDgGteTG5HBVFxYgRCISk7zTbNT8OBXI4K+CB1QNbp8q6N/v93tiOr6KlpA+8c5Vp9KizwvK5CUaAJ0uLGZvpVvoOhxXYvPyMlZYnIabK2haa30omao/v5/m4Ro0aFAv/tSNlHL/cJ21ud9VVaUiGqUSA+/W2caChNeQboqoVosVFoePAAVCVOo7kEAzpnhsRGsWWexnMUbK5iS5Bnn5u9bLMfgBiGqgy3EGzBbVn/zrpr26J0MlbuEhVy4Y5i93aiFwhP6h9mQqoleKgGaa3vfi5wNYZNjkSEJgDWSCLgHLYFMjJyk7VzXh++M9iLYzSg0CiMEqPwknqNVqR5BCvBelVUP8WoDPro4oEe4yvuqbYY0LlDQeaVANZB10fW/ZfBOEfwsOZ7bKx+mk38waM73UrUJ+fq6irrH3n/rndjhZfQnq+mPcW2SLrB5kzhTCpBkeq7kDBrPE1DpDqNvWto0CoSsSZXS/dF8wiBzgUngoIA=
  app:
    main: moz-locallibrary
  run:
  - python manage.py migrate --noinput
